export const AUTHENTICATION = '@@redux/LOGIN/AUTHENTICATION'
export const LOGOUT = '@@redux/LOGIN/LOGOUT'
export const LOGIN_SUCCESS = '@@redux/LOGIN/LOGIN_SUCCESS'
export const LOGIN_ERROR = '@@redux/LOGIN/LOGIN_ERROR'
export const RESET_STORE = '@@redux/LOGIN/RESET_STORE'

export const SET_COMFIRMATION_OTP = '@@redux/OTP/SET_COMFIRMATION_OTP'
export const SET_USER_AUTHPHONE = '@@redux/OTP/SET_USER_AUTHPHONE'

export const REGISTER_NEW_USER = '@@redux/REGISTER/REGISTER_NEW_USER'
export const SAVE_FORM_REGISTER = '@@redux/REGISTER/SAVE_FORM_REGISTER'
export const REGISTER_REJECTED = '@@redux/REGISTER/REGISTER_REJECTED'

export const GET_USER_FULLFILLED = '@@redux/USER/GET_USER_FULLFILLED'
