export const GET_CATEGORY = '@@redux/CATEGORY/GET_CATEGORY'
export const GET_CATEGORY_FULFILLED = '@@redux/CATEGORY/GET_CATEGORY_FULFILLED'
export const GET_CATEGORY_REJECTED = '@@redux/CATEGORY/GET_CATEGORY_REJECTED'
export const RESET_STORE = '@@redux/CATEGORY/RESET_STORE'
