export const CHECKOUT_LOADING = '@@redux/CHECKOUT/CHECKOUT_LOADING'
export const CHECKOUT_DATA_FULFILLED =
  '@@redux/CHECKOUT/CHECKOUT_DATA_FULFILLED'
export const CHECKOUT_DATA_REJECT = '@@redux/CHECKOUT/CHECKOUT_DATA_REJECT'
export const RESET_STORE = '@@redux/CHECKOUT/RESET_STORE'
