export const GET_COMMENT = '@@redux/COMMENT/GET_COMMENT'
export const GET_COMMENT_FULFILLED = '@@redux/COMMENT/GET_COMMENT_FULFILLED'
export const GET_COMMENT_REJECTED = '@@redux/COMMENT/GET_COMMENT_REJECTED'
export const RESET_STORE = '@@redux/COMMENT/RESET_STORE'

export const POST_COMMENT_LOADING = '@@redux/COMMENT/POST_COMMENT_LOADING'
export const POST_COMMENT_FULFILLED = '@@redux/COMMENT/POST_COMMENT_FULFILLED'
export const POST_COMMENT_REJECTED = '@@redux/COMMENT/POST_COMMENT_REJECTED'
