export const GET_ADDRESS = '@@redux/DELIVERY/GET_ADDRESS'
export const GET_ADDRESS_FULLFILLED = '@@redux/DELIVERY/GET_ADDRESS_FULLFILLED'
export const GET_ADDRESS_REJECTED = '@@redux/DELIVERY/GET_ADDRESS_REJECTED'
export const RESET_STORE = '@@redux/DELIVERY/RESET_STORE'

export const UPDATE_ADDRESS_LOADING = '@@redux/DELIVERY/UPDATE_ADDRESS_LOADING'
export const UPDATE_ADDRESS_FULLFILLED =
  '@@redux/DELIVERY/UPDATE_ADDRESS_FULLFILLED'
export const UPDATE_ADDRESS_REJECTED =
  '@@redux/DELIVERY/UPDATE_ADDRESS_REJECTED'

export const GET_USER_FULLFILLED = '@@redux/DELIVERY/GET_USER_FULLFILLED'

export const GET_SHIPPING_FULLFILLED =
  '@@redux/DELIVERY/GET_SHIPPING_FULLFILLED'

export const CHOICE_DELIVERY_OPTION = '@@redux/DELIVERY/CHOICE_DELIVERY_OPTION'
