export const GET_DETAIL_ORDER_FULFILLED =
  '@@redux/ORDER/GET_DETAIL_ORDER_FULFILLED'
export const GET_DETAIL_ORDER_REJECT = '@@redux/ORDER/GET_DETAIL_ORDER_REJECT'
export const DELETE_DETAIL_ORDER = '@@redux/ORDER/DELETE_DETAIL_ORDER'
export const DELETE_DETAIL_ORDER_FULFILLED =
  '@@redux/ORDER/DELETE_DETAIL_ORDER_FULFILLED'
export const DELETE_DETAIL_ORDER_REJECT =
  '@@redux/ORDER/DELETE_DETAIL_ORDER_REJECT'

export const GET_ORDERS_LOADING = '@@redux/ORDER/GET_ORDERS_LOADING'
export const GET_LIVE_ORDERS_FULFILLED =
  '@@redux/ORDER/GET_LIVE_ORDERS_FULFILLED'
export const GET_MEMBER_ORDERS_FULFILLED =
  '@@redux/ORDER/GET_MEMBER_ORDERS_FULFILLED'
export const GET_ORDERS_LOADMORE = '@@redux/ORDER/GET_ORDERS_LOADMORE'
export const GET_ORDERS_REJECT = '@@redux/ORDER/GET_ORDERS_REJECT'

export const GET_ORDERS_STATUS = '@@redux/ORDER/GET_ORDERS_STATUS'

export const RESET_STORE = '@@redux/ORDER/RESET_STORE'
