export const GET_PRODUCT_DETAIL = '@@redux/GET_PRODUCT_DETAIL'
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'

export const GET_RELATE_PRODUCT = '@@redux/DETAIL_PRODUCT/GET_RELATE_PRODUCT'
export const GET_RELATE_PRODUCT_FAIL =
  '@@redux/DETAIL_PRODUCT/GET_RELATE_PRODUCT_FAIL'
export const GET_RELATE_PRODUCT_SUCCESS =
  '@@redux/DETAIL_PRODUCT/GET_RELATE_PRODUCT_SUCCESS'
