export const GET_PRODUCT = '@@redux/SHOPPING/GET_PRODUCT'
export const GET_PRODUCT_FULFILLED = '@@redux/SHOPPING/GET_PRODUCT_FULFILLED'
export const GET_PRODUCT_REJECTED = '@@redux/SHOPPING/GET_PRODUCT_REJECTED'
export const REFRESH_PRODUCT_FULFILLED =
  '@@redux/SHOPPING/REFRESH_PRODUCT_FULFILLED'
export const RESET_STORE = '@@redux/SHOPPING/RESET_STORE'
export const RESET_PRODUCT = '@@redux/SHOPPING/RESET_PRODUCT'
